version: "3"

services:
  backend:
    build: ./backend
    container_name: challenge-backend
    entrypoint: ./.docker/entrypoint.sh
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./backend:/home/node/app

  frontend:
    build: ./frontend
    container_name: challenge-frontend
    entrypoint: ./.docker/entrypoint.sh
    restart: always
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/home/node/app
